services:
  db-postgres:
    container_name: db-postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: Partikar
      POSTGRES_PASSWORD: Partikar1234
      POSTGRES_DB: partikardb
    ports:
      - "5432:5432"
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/target
    depends_on:
      - db-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/partikardb
      SPRING_DATASOURCE_USERNAME: Partikar
      SPRING_DATASOURCE_PASSWORD: Partikar1234

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_URL=http://backend:8080
    command: [ "npm","run","dev","--","--host" ]
    depends_on:
      - backend


volumes:
  db-postgres-data:
